name: simple_sidebar
description: A very simple sidebar with Icons, Texts, Header and smoothing. Easy to implement and easy to use
version: 0.0.5
homepage: hhttps://github.com/felixkriechbaum/SimpleSidebar

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
